###
# PING
GET http://localhost:8000/api/v1/ping

###
# Revert vector
POST http://localhost:8000/api/v1/revert_vector
Content-Type: application/json

[1, 2, 3, 4, 5]

###
# Revert string
POST http://localhost:8000/api/v1/revert_vector
Content-Type: application/json

"string"

###
# Unknown route
GET http://localhost:8000/unknow
